export * from './ForgotPasswordRoute'
export * from './CustomerRoute'
export * from './ProductRoute'
export * from './DashboardRoute'
export * from './ProfileRoute'
export * from './StocksRoute'
export * from './SuppliersRoute'
export * from './PaymentsRoute'
export * from './SettingsRoute'
export * from './PriceListRoute'

export * from './LandingRoute'
export * from './LoginRoute'
export * from './ForgotPasswordRoute'
