export { default as Dashboard } from './Dashboard/Dashboard.tsx'
export { default as Customer } from './Customer/Customer.tsx'
export { default as Profile } from './Profile/Profile.tsx'
export { default as Products } from './Products/Products.tsx'
export { default as Login } from './Login/Login.tsx'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword.tsx'
export { default as Suppliers } from './Suppliers/Suppliers.tsx'
export { default as Stocks } from './Stocks/Stocks.tsx'
export { default as Payments } from './Payments/Payments.tsx'
export { default as Settings } from './Settings/Settings.tsx'

export { default as Attendance } from './Attendance/Attendance.tsx'
export { default as Help } from './Help/Help.tsx'
export { default as Staff } from './Staff/Staff.tsx'
export { default as Sales } from './Sales/Sales.tsx'
export { default as Category } from './Category/Category.tsx'
export { default as Purchase } from './Purchase/Purchase.tsx'
export { default as Landing } from './Landing/Landing.tsx'
export { default as PriceList } from './PriceList/PriceList.tsx'

export { default as Invoice } from './Invoice/Invoice.tsx'
export { default as SalesOrder } from './Sales/SalesOrder.tsx'
export { default as SalesReturn } from './Sales/SalesReturn.tsx'

export { default as PaymentsReceived } from './PaymentsReceived/PaymentsReceived.tsx'
export { default as DeliveryReceipts } from './DeliveryReceipts/DeliveryReceipts.tsx'
export { default as Packaging } from './Packaging/Packaging.tsx'
export { default as Shipments } from './Shipments/Shipments.tsx'
export { default as PurchaseOrders } from './PurchaseOrders/PurchaseOrders.tsx'
export { default as PurchaseReceived } from './PurchaseReceived/PurchaseReceived.tsx'
export { default as Bill } from './Bill/Bill.tsx'
export { default as Credits } from './Credits/Credits.tsx'

export { default as Roles } from './Roles/Roles.tsx'
